### ISSUE TITLE
Setup theme hierarchy in .json

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#16]
Setup a multi-brand theme hierarchy in Figma Tokens for all SL core products.

**To be discussed**
- Which brands do we support?
- How to support mobile sizing?
- Light/Dark mode
- What's core?
- What's base?

**Structure**
- Core (which is standard for all products)
- Base (contains color palette, typography)
- Scaling desktop/mobile/presentation
  - Contains all the sizing/spacing/typography that is different between desktop & mobile
  - No color tokens here
- Color scheme (light/dark)
  - Contains the light/dark specific tokens + component tokens
  - No spacing/sizing tokens here

Example: 
- core + base + mobile + dark
- core + base + desktop + light
- core + base + presentation + light

**Discussed**
- Setup Sanoma Learning theme first
- Generate other themes when SL theme is ready and approved

**Comment by jpzwarte** [comment]
The sanoma-learning theme contains empty files (for now) for desktop & mobile:
<img width="147" alt="Screenshot 2022-10-26 at 10 06 04" src="https://user-images.githubusercontent.com/3968/197970300-8bbced97-4a9d-4231-a582-1ccb09f9a307.png">
